# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aaditya Prakash Kattekola
# email: aadityapra2910@gmail.com
# description: ""
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kapi2910.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: avatar.jpg
# twitter_username: Kapi2910
# github_username: Kapi2910

# Basic Information 
title: Aaditya Prakash Kattekola
position: Ph.D Student
affiliation: University of California, Santa Barbara
email: aadityaprakash@ucsb.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
# keywords: minimal light
# description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
# canonical: https://minimal-light-theme.yliu.me/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=dUyBIokAAAAJ&hl=en
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/Kapi2910
linkedin: https://www.linkedin.com/in/kapi2910/
twitter: https://twitter.com/Kapi2910

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon_io/favicon.ico
favicon_dark: ./assets/img/favicon_io/favicon.ico

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

github:
  {
    is_user_page: true,
    is_project_page: false,
    owner_url: https://github.com/Kapi2910,
  }

# Build settings
remote_theme: yaoyao-liu/minimal-light
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
